/*******************************************************************************
 * File Name: project.h  
 * PSoC Creator 2.2 Component Pack 5
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2011, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/
#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <Motor_1_function.h>
#include <Pin_1_aliases.h>
#include <Pin_1.h>
#include <Pin_2_aliases.h>
#include <Pin_2.h>
#include <Pin_3_aliases.h>
#include <Pin_3.h>
#include <Pin_4_aliases.h>
#include <Pin_4.h>
#include <Clock_1.h>
#include <Motor_1_PWM_2.h>
#include <Motor_1_PWM_1.h>
#include <Motor_1_PWM_8.h>
#include <Motor_1_PWM_7.h>
#include <Motor_1_PWM_6.h>
#include <Motor_1_PWM_5.h>
#include <Motor_1_PWM_4.h>
#include <Motor_1_PWM_3.h>
#include <Motor_1_Status_Reg_1.h>
#include <Motor_1_Control_Reg_1.h>
#include <Motor_1_PWM_9.h>
#include <Motor_1_PWM_10.h>
#include <Motor_1_PWM_11.h>
#include <Motor_1_PWM_12.h>
#include <Motor_1_PWM_13.h>
#include <Motor_1_PWM_14.h>
#include <Motor_1_PWM_15.h>
#include <Motor_1_PWM_16.h>
#include <Motor_1_Timer_1.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>

/*[]*/
